// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzect3ri-cFs5l5DY0Bw8MUtAUBE7iJNw',
    appId: '1:234138813499:web:7ee63757fe9aa41de4881e',
    messagingSenderId: '234138813499',
    projectId: 'conta-pontos',
    authDomain: 'conta-pontos.firebaseapp.com',
    storageBucket: 'conta-pontos.appspot.com',
    measurementId: 'G-GNDTG7K47D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KbB0A2UFwG0y32r85c3tIEdFRHp3SVM',
    appId: '1:234138813499:android:ec9ec6cb2d5fed87e4881e',
    messagingSenderId: '234138813499',
    projectId: 'conta-pontos',
    storageBucket: 'conta-pontos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQHeS0UPIfnnUe0uu5HpW2Mpv2ZgTJYFA',
    appId: '1:234138813499:ios:2ee59eb81ca10652e4881e',
    messagingSenderId: '234138813499',
    projectId: 'conta-pontos',
    storageBucket: 'conta-pontos.appspot.com',
    iosBundleId: 'com.example.contaponto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQHeS0UPIfnnUe0uu5HpW2Mpv2ZgTJYFA',
    appId: '1:234138813499:ios:73a9625bb44fa0e6e4881e',
    messagingSenderId: '234138813499',
    projectId: 'conta-pontos',
    storageBucket: 'conta-pontos.appspot.com',
    iosBundleId: 'com.example.contaponto.RunnerTests',
  );
}
